### ISSUE TITLE
Error! Bad Return status for module build on kernel: 6.9.0-1-MANJARO (x86_64)

### ISSUE THREAD

**Issue by lithiumfox** [JacKeTUs/vrs-ff#1]
**Issue:** 

Error! Bad Return status for module build on kernel: 6.9.0-1-MANJARO (x86_64)
when attempting to install via dkms or via manual build

**Command Run:**
sudo dkms install /usr/src/vrs-ff
Sign command: /usr/lib/modules/6.9.0-1-MANJARO/build/scripts/sign-file
Signing key: /var/lib/dkms/mok.key
Public certificate (MOK): /var/lib/dkms/mok.pub
Creating symlink /var/lib/dkms/vrs-ff/0.0.1/source -> /usr/src/vrs-ff-0.0.1

Building module:
Cleaning build area...
make -j24 KERNELRELEASE=6.9.0-1-MANJARO KVERSION=6.9.0-1-MANJARO...(bad exit status: 2)
Error! Bad return status for module build on kernel: 6.9.0-1-MANJARO (x86_64)
Consult /var/lib/dkms/vrs-ff/0.0.1/build/make.log for more information.

**Log File:**
[make.log](https://github.com/JacKeTUs/vrs-ff/files/15444799/make.log)

**Comment by JacKeTUs** [comment]
Pls try again with new commits

**Comment by lithiumfox** [comment]
No errors running command. I have to wait for a reboot, in the middle of FFXIV stuff. :) I'll let you know how it goes after reboot.

**Comment by JacKeTUs** [comment]
Closing, because we're already successfully tested new version of the driver :)
